from .minicpmv_gptq_plus import minicpmv_rtn_gptq_fwrd_plus
from .qwenvl_gptq_plus import qwenvl_rtn_gptq_fwrd_plus
from .internvl_gptq_plus import internvl_rtn_gptq_fwrd_plus
from .qwen2vl_gptq_plus import qwen2vl_rtn_gptq_fwrd_plus
from .janus_gptq_plus import janus_rtn_gptq_fwrd_plus
